### ISSUE TITLE
一致性hash

### ISSUE THREAD

**Issue by qixiaobo** [yiding-he/hydrogen-ssdb#1]
话说你这个
`
protected List<Cluster> clusters = new ArrayList<Cluster>();
 Cluster cluster = clusters.get(i);
            int min, max;

            if (i == clusters.size() - 1) {
                min = ((int) (pointer + Integer.MIN_VALUE) + 1);
                max = (Integer.MAX_VALUE);
                setClusterRange(cluster, min, max);

            } else {
                min = i == 0 ? Integer.MIN_VALUE : (int) (pointer + Integer.MIN_VALUE) + 1;

                weightcounter += cluster.getWeight();
                pointer = maxrange * weightcounter / maxWeight;
                max = ((int) (pointer + Integer.MIN_VALUE));

                setClusterRange(cluster, min, max);
            }`
这个应该和你放入的顺序有关了吧，假设你的顺序更换了，我所有的分片都会乱掉了。
最好支持可以带名称的集群

**Comment by yiding-he** [comment]
对，这个问题确实存在，如果不能严格的给定顺序，就有可能出现混乱。现在 Cluster 类已经有一个 id 属性，可以用来命名：

```
<bean id="namedCluster" class="com.hyd.ssdb.conf.Cluster" factory-method="fromSingleServer">
    <constructor-arg name="server" ref="ssdbServer1"/>
    <property name="id" value="cluster1"/>
</bean>
```

但命名本身不能表达出顺序的含义，更合适的方式也许是在 cluster 的定义里面加个属性直接表示位置顺序。

**Comment by yiding-he** [comment]
1、一致性哈希中，Cluster 的顺序是不能够变更的。这点需要特别注意。
2、com.hyd.ssdb.conf.Sharding#getClusterById(String) 方法可以根据 ID 获取指定的 Cluster 配置。
