### ISSUE TITLE
接口异常和返回值设计问题

### ISSUE THREAD

**Issue by kkfnui** [yiding-he/hydrogen-ssdb#10]
**第一：设计问题**

```
public int getIntResult() {
        if (header.equals("not_found")) {
            return -1;
        } else {
            return Integer.parseInt(firstBlock());
        }
    }
```

返回 -1 ，在语义层面是有两个问题:
1. 不能很明显的反应没有获取到数据
2. 会混淆值为 -1 和 没有查询到数据的情况

**第二：接口异常**

接口 `zget` 在获取不存在数据的时候，会抛异常。其他类似接口应该也有同样问题。

**最后： 修改建议**
1. 内部捕获转型失败的异常
2. 修改返回值类型，将 `int` `long` 分别修改成 `Integer` `Long`。通过 null 表示查询的结果不存在。

**Comment by yiding-he** [comment]
### 关于 -1 返回值：

一般来说，作为命令的执行结果，返回 -1 是没有意义的。下面列出了所有用到这个方法的地方，我自己看了一下，貌似不会有歧义。如果确实存在，还请指出来，谢谢

![qq 20160623165217](https://cloud.githubusercontent.com/assets/900606/16297326/f4cc902a-3962-11e6-8567-d953f4107782.png)

### 关于 zget 异常

下面是我补充的测试代码：

```java
    @Test
    public void testZget() throws Exception {
        ssdbClient.zclear("yuwen");
        ssdbClient.zclear("shuxue");
        ssdbClient.zset("yuwen", "zhangsan", 100);
        ssdbClient.zset("yuwen", "lisi", 101);
        assertEquals(100, ssdbClient.zget("yuwen", "zhangsan"));
        assertEquals(-1, ssdbClient.zget("yuwen", "wangwu"));
        assertEquals(-1, ssdbClient.zget("shuxue", "wangwu"));
    }
```

运行该测试并未发现异常。如果你运行的 SSDB 服务器是 Windows 版的，那个太坑爹，我不打算兼容。

**Comment by penuel-leo** [comment]
如果 zset test key -1,那么zget返回的-1是值还是not_found?

**Comment by yiding-he** [comment]
@penuel-leo  这个问题确实存在，感谢反馈。年底事多，不会马上搞定，但争取在过年前提交修复。

**Comment by yiding-he** [comment]
问题已修复（[commit](https://github.com/yiding-he/hydrogen-ssdb/commit/d826e4f73c70c20e7f69a35aa661406292c7d9fa)）
