### ISSUE TITLE
bug 提交

### ISSUE THREAD

**Issue by streammemoryli** [yiding-he/hydrogen-ssdb#12]
Response的getBytes方法实现不正确，不应该调用toBytes方法，盼修正

  public byte[] getBytes() {
        return this.body.isEmpty() ? new byte[0] : this.body.get(0).toBytes();
    }

**Comment by yiding-he** [comment]
感谢提建议，我会检查一下。

**Comment by yiding-he** [comment]
能否具体说明一下，为什么不应该调用 `com.hyd.ssdb.protocol.Block.toByes()`，这个方法有什么问题？

**Comment by streammemoryli** [comment]
用Kryo序列化对象后的长度，和从ssdb取出的长度不一致，反序列化失败
其它情况没有试过
直接返回block 中的 data 时，长度与存入前（系列化后）一致，反序列化成功

**Comment by yiding-he** [comment]
已修复，感谢反馈！
