### ISSUE TITLE
zscan,zrscan,zkeys命令错误

### ISSUE THREAD

**Issue by penuel-leo** [yiding-he/hydrogen-ssdb#14]
正常ssdb命令参数应该是"name,key_start,score_start,score_end,limit"，但ssdbclient里面的是"key,startExclude,endInclude,limit"参数错误，执行会报client_error.
实际上ssdb server返回的错误是 
`server.cpp(340): w:0.061,p:0.007, req: zscan key1 "" "" 10, resp: client_error wrong number of arguments`
建议后续大家使用更改如下:
`public List<IdScore> zscan(String name,String keyStart, Long scoreStart, Long scoreEnd, int limit)`
`{`
`        return sendRequest("zscan", name, keyStart, scoreStart==null?"":scoreStart.longValue(),  scoreEnd==null?"":scoreEnd.longValue(), limit).getIdScores();`
  `}`

**Comment by yiding-he** [comment]
@penuel-leo  问题已修复（[commit](https://github.com/yiding-he/hydrogen-ssdb/commit/4905e31ad9b6762733f038d30bd4cc9b955e7ab5)），感谢反馈！
