### ISSUE TITLE
服务器故障恢复不了的问题

### ISSUE THREAD

**Issue by zhuhc1991** [yiding-he/hydrogen-ssdb#15]
升级了最新的jar包，但是测试时，仍不能解决服务器故障，恢复不了的问题，请问下，还需要什么配置的吗

**Comment by yiding-he** [comment]
目前只实现了一个主从 Cluster 中的某台服务器挂掉然后恢复的情况。

如果整个 Cluster 挂掉，那么这个 Cluster 就会被删除，恢复后也不能自动加回来。

这两天修复一下这个问题。

**Comment by zhuhc1991** [comment]
那用了集群的，是不是也是这样呀

**Comment by zhuhc1991** [comment]
请问下，多个Cluster ，其中 一个Cluster 一个服务器
当有个服务器挂了，那所属的Cluster 也被删了？？？
这个服务器恢复了，那也就加不回来，是这个意思吗？？？

**Comment by yiding-he** [comment]
这里有问题，就是一个 Cluster 恢复之后应该放到哈希环的哪个位置。简单的情况下，如果只有一个 Cluster 挂掉并恢复，是可以找到它的原来位置的，而如果同时挂掉几个 Cluster，甚至所有服务器都无法连接，然后再恢复就不容易找回位置了……

**Comment by zhuhc1991** [comment]
┭┮﹏┭┮

**Comment by yiding-he** [comment]
刚刚修复了， @zhuhc1991 欢迎有时间测下，谢谢

**Comment by zhuhc1991** [comment]
嗯嗯，我测试看看

**Comment by zhuhc1991** [comment]
不知为啥有时执行者执行者，就会报这个错。。。。ssdb都处于正常
2017-08-07 10:23:30,901 [pool-9-thread-76382] ERROR com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:100) Connection failed: 
com.hyd.ssdb.SsdbNoClusterAvailableException: ALL CLUSTERS DOWN
	at com.hyd.ssdb.sharding.ConsistentHashSharding.getClusterByKey(ConsistentHashSharding.java:268)
	at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:69)
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:110)
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:88)
	at com.hyd.ssdb.SsdbClient.get(SsdbClient.java:102)
	at com.asiainfo.common.redis.ssdb.SsdbKVMap.get(SsdbKVMap.java:29)

**Comment by zhuhc1991** [comment]
@Override
    public Cluster getClusterByKey(String key) {

        if (noClusterAvailable()) {
            throw new SsdbNoClusterAvailableException("ALL CLUSTERS DOWN");
        }
      。。。。。。
    }

看代码，这里判断集群是否正常的，为啥会不正常呢
是因为脏数据的原因吗

**Comment by zhuhc1991** [comment]
但是大多数获取该集群是没问题的

**Comment by yiding-he** [comment]
@zhuhc1991 

* 首先你的实际运行环境是什么样的，有几个 cluster，每个 cluster 有几个 ssdb 实例；
* 其次你的 ssdb 连接超时设置是否合适，缺省在 `com.hyd.ssdb.conf.SocketConfig#DEFAULT_SO_TIMEOUT` 里是一秒钟，这个可以通过 `com.hyd.ssdb.conf.Server#setSocketConfig()` 修改；
* 再次每个 server 被检查到无法连接时，会每隔 15 秒检查一次，在此期间改 server 会直接被认定是无效的。这个间隔时长可以通过调用 `com.hyd.ssdb.conn.ServerMonitorDaemon#setInterval()` 来修改。

**Comment by zhuhc1991** [comment]
1）实际运行环境是：有两个cluster，每个cluster一个ssdb_ 服务器
2）每个ssdb连接超时设为20秒
3）我停了ssdb，之后再开启ssdb的，没有修改配置

**Comment by yiding-he** [comment]
@zhuhc1991 在出现 "ALL CLUSTERS DOWN" 之前是否有报 "Connection error" 异常？具体内容是什么？

**Comment by zhuhc1991** [comment]
停了ssdb就有报，之后启动ssdb，每请求一次，就报"ALL CLUSTERS DOWN" 
写个测试用例，测试是没问题的┭┮﹏┭┮

**Comment by zhuhc1991** [comment]
目前，测试到，倘若全部集群挂了，是没恢复的

**Comment by yiding-he** [comment]
我明天测下看看。

**Comment by zhuhc1991** [comment]
可以请问一下，恢复了，请求时，第一次请求总会失败，后面再请求都没问题了。。。神奇，想不明白为啥会这样。。。是请求触发恢复的吗

**Comment by zhuhc1991** [comment]
写了个类似当前的实际运行环境测试用例  ，如下
public static void main(String[] args) throws Exception {
        ServerMonitorDaemon.setInterval(3000);
        SsdbClient ssdbClient1 = new SsdbClient(new ConsistentHashSharding(
                Cluster.fromSingleServer("127.0.0.1",8888),
                Cluster.fromSingleServer("127.0.0.1",8889)
        ));

        SsdbClient ssdbClient2 = new SsdbClient("127.0.0.1",8888);
        SsdbClient ssdbClient3 = new SsdbClient("127.0.0.1",8889);


        ssdbClient1.del("name1");  // init
        ssdbClient2.del("name2");  // init
        ssdbClient3.del("name3");  // init


        ssdbClient1.set("name1","name1");  // init
        ssdbClient2.set("name2","name2");  // init
        ssdbClient3.set("name3","name3");  // init

        while (true) {
            try {
                System.out.println(ssdbClient1.get("name1"));
            }  catch (Exception e) {
                System.err.println(e.toString());
            }
            try {
                System.out.println(ssdbClient2.get("name2"));
            }  catch (Exception e) {
                System.err.println(e.toString());
            }
            try {
                System.out.println(ssdbClient3.get("name3"));
            } catch (Exception e) {
                System.err.println(e.toString());
            }
            System.out.println(".............................");
            Thread.sleep(3000);
        }

        //ssdbClient.close();
    }

我设置的检测时间是3秒的。
开启ssdb（8888,8889），过段时间停了ssdb（8888），再开启ssdb（8888），结果是这样的：ssdbClient1，是没法恢复的，ssdbClient2可以恢复。

以下是执行日志：
14:58:07 [DEBUG] c.h.s.c.ConnectionFactory:36 - Creating connection with Server{host='127.0.0.1', port=8888, master=true}
14:58:07 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(del): [ok] - (1 blocks)
14:58:07 [DEBUG] c.h.s.c.ConnectionFactory:36 - Creating connection with Server{host='127.0.0.1', port=8888, master=true}
14:58:07 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(del): [ok] - (1 blocks)
14:58:07 [DEBUG] c.h.s.c.ConnectionFactory:36 - Creating connection with Server{host='127.0.0.1', port=8889, master=true}
14:58:07 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(del): [ok] - (1 blocks)
14:58:07 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(set): [ok] - (1 blocks)
14:58:07 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(set): [ok] - (1 blocks)
14:58:07 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(set): [ok] - (1 blocks)
14:58:07 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [ok] - (1 blocks)
name1
14:58:07 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [ok] - (1 blocks)
name2
14:58:07 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [ok] - (1 blocks)
name3
.............................


。。。。。。。。。


.............................
14:58:40 [ERROR] c.h.s.AbstractClient:118 - Connection error
com.hyd.ssdb.SsdbSocketFailedException: java.net.SocketException: Connection reset by peer: socket write error
	at com.hyd.ssdb.conn.Connection.send(Connection.java:84) ~[classes/:na]
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:142) [classes/:na]
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:113) [classes/:na]
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:86) [classes/:na]
	at com.hyd.ssdb.SsdbClient.get(SsdbClient.java:101) [classes/:na]
	at com.hyd.ssdb.InvalidClusterTest.main(InvalidClusterTest.java:41) [test-classes/:na]
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_91]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[na:1.8.0_91]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:141) ~[na:1.8.0_91]
	at com.hyd.ssdb.conn.Connection.send(Connection.java:80) ~[classes/:na]
	... 5 common frames omitted
14:58:40 [ERROR] c.h.s.c.Cluster:250 - Server unavailable: Server{host='127.0.0.1', port=8888, master=true}
14:58:40 [DEBUG] c.h.s.s.ConsistentHashSharding:229 - Expand cluster 127.0.0.1:8889 left to ring start.
14:58:40 [ERROR] c.h.s.c.ConnectionPoolManager:94 - Connection failed: 
com.hyd.ssdb.SsdbNoServerAvailableException: Unable to find server in cluster '127.0.0.1:8888'
	at com.hyd.ssdb.conf.Cluster.getRandomServer(Cluster.java:233) ~[classes/:na]
	at com.hyd.ssdb.conn.ConnectionPoolManager.pickServer(ConnectionPoolManager.java:124) ~[classes/:na]
	at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:70) ~[classes/:na]
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:107) [classes/:na]
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:86) [classes/:na]
	at com.hyd.ssdb.SsdbClient.get(SsdbClient.java:101) [classes/:na]
	at com.hyd.ssdb.InvalidClusterTest.main(InvalidClusterTest.java:41) [test-classes/:na]
14:58:40 [DEBUG] c.h.s.c.ConnectionFactory:36 - Creating connection with Server{host='127.0.0.1', port=8889, master=true}
14:58:40 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [not_found] - (0 blocks)
null
14:58:40 [ERROR] c.h.s.AbstractClient:118 - Connection error
com.hyd.ssdb.SsdbSocketFailedException: java.net.SocketException: Connection reset by peer: socket write error
	at com.hyd.ssdb.conn.Connection.send(Connection.java:84) ~[classes/:na]
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:142) [classes/:na]
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:113) [classes/:na]
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:86) [classes/:na]
	at com.hyd.ssdb.SsdbClient.get(SsdbClient.java:101) [classes/:na]
	at com.hyd.ssdb.InvalidClusterTest.main(InvalidClusterTest.java:46) [test-classes/:na]
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_91]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[na:1.8.0_91]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:141) ~[na:1.8.0_91]
	at com.hyd.ssdb.conn.Connection.send(Connection.java:80) ~[classes/:na]
	... 5 common frames omitted
14:58:40 [ERROR] c.h.s.c.Cluster:250 - Server unavailable: Server{host='127.0.0.1', port=8888, master=true}
14:58:40 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [ok] - (1 blocks)
name3
.............................
com.hyd.ssdb.SsdbNoClusterAvailableException: No cluster exists
14:58:42 [INFO ] c.h.s.c.Cluster:270 - Server restored: Server{host='127.0.0.1', port=8888, master=true}
14:58:43 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [not_found] - (0 blocks)
null
14:58:43 [DEBUG] c.h.s.c.ConnectionFactory:36 - Creating connection with Server{host='192.168.133.128', port=8888, master=true}
14:58:43 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [ok] - (1 blocks)
name2
14:58:43 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [ok] - (1 blocks)
name3
.............................
。。。。。

15:19:10 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [not_found] - (0 blocks)
null
15:19:10 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [ok] - (1 blocks)
name2
15:19:10 [DEBUG] c.h.s.AbstractClient:157 - RESPONSE(get): [ok] - (1 blocks)
name3
.............................


就是后面ssdbClient1一直用的是8889的，所以一直输出null，而没有恢复8888进ssdbClient1


但是检测时间默认是15秒的话，倘若ssdbClient1先恢复，后面的ssdbClient2也可以恢复的

这个怎么一回事？？？

是多个客户端，导致检测的类检测有问题吗？？

**Comment by zhuhc1991** [comment]
还是检测时间设置的问题？？

**Comment by yiding-he** [comment]
@zhuhc1991 我测试了一下，日志输出在附件中
[hydrogen-ssdb.log.zip](https://github.com/yiding-he/hydrogen-ssdb/files/1213919/hydrogen-ssdb.log.zip)

这个日志的执行环境模拟了包含两个 cluster 的环境（分别是端口 18880 和 18881），运行代码是在项目中的测试目录下的 `com.hyd.ssdb.InvalidClusterTest` 类。

从日志内容中看到的信息是：

* 时间15:11:16第4行，报超时错误，之后21行给出了详细信息：端口18880的服务器下线。注意这时候开始将会每隔15秒检查一次，因此下次检查将会在15:11:31。
* 因为该服务器是 Cluster 中唯一的，因此24行给出错误信息：整个Cluster下线。
* 时间15:11:25第74行，端口18881的服务器同样出现超时。
* 从这之后开始，因为两个 Cluster 都下线，一直报错 "NO CLUSTER AVAILABLE"（这个错误以前是 "ALL CLUSTER DOWN"，后面改了下文字内容）。
* 直到时间15:11:31第195行，程序检查到18881服务器恢复，于是后面几行又正常输出了，直到时间15:11:37再次超时。

从后面的日志内容基本上可以看出，只要服务器恢复可用，SsdbClient 还是会检查到并恢复正常运作的。

**Comment by zhuhc1991** [comment]
嗯嗯，你这个没问题，我的还多个客户端的

**Comment by zhuhc1991** [comment]
问题是上面我描述那里：
![default](https://user-images.githubusercontent.com/24652143/29159567-9b945ffa-7de1-11e7-96e1-37be5b28b3f9.png)

**Comment by zhuhc1991** [comment]
ServerMonitorDaemon.setInterval(3000);，我这样子设置检测时间是不是有问题呀，不知道为啥，有的可以恢复，有的没有恢复的

**Comment by yiding-he** [comment]
@zhuhc1991 

知道怎么回事了，设计的时候没有考虑多个 SsdbClient 连接到同一个 ssdb 服务器的情况，因为实际情况下不太可能会这么做。

首先，对无效的服务器检查是共用一个 ServerMonitorDaemon，这个类的所有方法都是静态的，也就是说不管多少个 SsdbClient 都是交给同一个地方去检查无效服务器；

当检查到一个 Server 恢复后，会查询其所属的 Cluster。这里问题来了，因为只要是 host 和 port 相同我就会认为是同一个 Server，而一个 Server 被视为只可能属于一个 Cluster，因此当一个 Server 恢复后，对应被恢复的 Cluster 也只会有一个。之后这个 Server 会从监视列表中删除，也就是说另一个包含该 Server 的 Cluster 再也不会恢复了。

**Comment by zhuhc1991** [comment]
我还以为一个客户端对应一个ServerMonitorDaemon，想着这样应该不会有问题的。
结果是多个 SsdbClient 共用一个 ServerMonitorDaemon
那按照你的设计思路，我得环境用不了了呢。。。因为我这边的实际环境是多个 SsdbClient 有可能连接到同一个 ssdb 服务器的。

**Comment by yiding-he** [comment]
@zhuhc1991 我刚提交修复了，欢迎测下

**Comment by zhuhc1991** [comment]
修复了？？嗯嗯，好的，我测测

**Comment by yiding-he** [comment]
鉴于没有进一步的反馈，本 issue 被关闭。
