### ISSUE TITLE
hlist接口问题

### ISSUE THREAD

**Issue by kr1s-gzq** [yiding-he/hydrogen-ssdb#16]
官方hlist接口文档写的好像不对，返回的应该是hash name的集合
官方hlist接口没有key这个参数，如果有了key参数，那和hscan是一样的了

 public List<KeyValue> hlist(String key, String startExclude, String endInclude, int limit) {
        return sendRequest("hlist", key, startExclude, endInclude, limit).getKeyValues();
 }

public List<KeyValue> hrlist(String key, String startExclude, String endInclude, int limit) {
        return sendRequest("hrlist", key, startExclude, endInclude, limit).getKeyValues();
}

**Comment by yiding-he** [comment]
收到，感谢反馈，我会在本周处理这个问题。当然也欢迎 PR。

**Comment by yiding-he** [comment]
@kr1s-gzq  修复已提交，欢迎测试

**Comment by yiding-he** [comment]
鉴于无后续反馈，关闭 issue
