### ISSUE TITLE
multi_get

### ISSUE THREAD

**Issue by hzwuhao8** [yiding-he/hydrogen-ssdb#17]
没有 找到该方法
因为某种原因 ，没有实现 该方法吗？

**Comment by yiding-he** [comment]
这个问题说起来比较复杂，但还是把它实现了。

如果你用的是多台 ssdb 服务器的集群，那么 `multiGet()` 方法实际上是对每个 key 依次调用 get 命令，因为这些 key 可能分布在不同的服务器上，而 multi_get 命令只能发送给一台服务器，所以会导致某些 key 取不到值。

如果你用的是单台 ssdb 服务器，则没这个问题，ssdbClient 会发送 multi_get 给那台唯一的服务器。

源码已经更新，欢迎进行测试并把结果反馈给我。

**Comment by hzwuhao8** [comment]
非常感谢。
