### ISSUE TITLE
Sharding类里没有找到fromServerList方法

### ISSUE THREAD

**Issue by runyu12345** [yiding-he/hydrogen-ssdb#18]
你好, 我今天把代码down下来看了下. 在测试的时候发现报错. 
SsdbClient client = new SsdbClient(Sharding.fromServerList(servers));
		client.set("name", "hydrogen-ssdb");    // 写入请求一定会发送给主服务器
		System.out.println(client.get("name")); // 读取请求会随机发送给任意一台服务器
案例中的  Sharding.fromServerList(servers)方法报错. 
我看了下源代码, Sharding类里边没有找到这个方法. 
这个方法是不用了没有更新使用demo吗? 还是其他原因?

**Comment by yiding-he** [comment]
抱歉，文档有误。已经修复。

```java
List<Server> servers = Arrays.asList(
        new Server("192.168.1.180", 8888, null, true),  // 主服务器
        new Server("192.168.1.180", 8889, null, false)  // 从服务器
);

SsdbClient client = SsdbClient.fromSingleCluster(servers);
client.set("name", "hydrogen-ssdb");    // 写入请求一定会发送给主服务器
System.out.println(client.get("name")); // 读取请求会随机发送给任意一台服务器
```

**Comment by runyu12345** [comment]
今天又测试了一下,
用了一个cluster, 里边有一主两从三个ssdb.
我让其中一个从挂掉了, 然后跑测试. 
这样没什么问题. 会把挂掉的从节点标记然后重试. 

问题出现在, 我把从节点重新开起来, 发现他恢复成master节点了. 原来的master也是在的.
这个应该是从节点恢复依然是从节点才对吧?  还是在设计的时候出于什么情况的考虑,设计成这个样子?
