### ISSUE TITLE
一个cluster中从节点挂掉重新恢复时, 会恢复成主节点.

### ISSUE THREAD

**Issue by runyu12345** [yiding-he/hydrogen-ssdb#19]
public void reportInvalidConnection(String host, int port) {
        Server toInvalidate = new Server(host, port);
        for (Cluster cluster : sharding.getClusters()) {
            if (cluster.containsServer(toInvalidate)) {
                cluster.markInvalid(toInvalidate);
            }
        }
    }
这段代码, 标记不可用的时候,new了一个server. 默认是master.
从节点也会被当成master标记为不可用,恢复从节点时, 从节点会恢复成主节点.

**Comment by yiding-he** [comment]
问题已修复。 @runyu12345 感谢反馈！
