### ISSUE TITLE
返回结果有时为null

### ISSUE THREAD

**Issue by NineF** [yiding-he/hydrogen-ssdb#20]
我测试了一下,ssdb数据库会将同一个socket连接在同时发生的操作的结果放在一个输出流中,导致了其他操作返回为null的情况,请问下除了对每个socket连接加个锁这种方式,还有其他什么好的办法

**Comment by yiding-he** [comment]
问题已收到，我先看看具体是什么情况。按照你的说法，因为 ssdb 是异步通信的，所以会导致返回内容和请求错配？

**Comment by NineF** [comment]
仔细看了一下..我有个地方弄错了...应该是对的...谢谢了哈
