### ISSUE TITLE
为啥不发布到maven中央仓库？

### ISSUE THREAD

**Issue by zhanglei-1987** [yiding-he/hydrogen-ssdb#22]
为啥不发布到maven中央仓库？

**Comment by yiding-he** [comment]
不好意思，纯粹是我懒，不想维护中央仓库的证书之类的。

**Comment by cosoc** [comment]
这没什么难度啊，大兄弟！这样会影响推广的

**Comment by yiding-he** [comment]
这样子，我发布到 github 上，可以直接用。
https://github.com/yiding-he/hydrogen-ssdb#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
