### ISSUE TITLE
使用密码连接时返回noauth错误

### ISSUE THREAD

**Issue by jimingmi** [yiding-he/hydrogen-ssdb#23]
尝试连接发送数据时，返回“noauth”异常。
初始化Client时已经设置pass参数，且对应参数本地terminal多次尝试均没有问题。
```java
SsdbClient client = new SsdbClient('127.0.0.1', 18888,"pass");
client.set("key", "value");//noauth error
```
仔细阅读源码后发现并没有在send数据前进行auth操作，不知是否是此处有问题。
如果是我的问题希望可以在README中加入关于校验密码的Demo，感谢！

**Comment by jimingmi** [comment]
使用版本为 1.1.2

**Comment by yiding-he** [comment]
感谢反馈，该问题已经做了修复，发布到版本 1.2.0 了：
https://github.com/yiding-he/hydrogen-ssdb/tree/1.2.0

若还有问题请继续反馈
