### ISSUE TITLE
老兄测试了一下1.2.1.想请问multiGet，multiSet 是否也可以支持byte[]

### ISSUE THREAD

**Issue by darkice1** [yiding-he/hydrogen-ssdb#26]
感谢

**Comment by yiding-he** [comment]
可以，正在改，不过遇到点问题

**Comment by darkice1** [comment]
66666
有什么需要配合的吗？我也配合一起，测试了几个ssdb的库感觉您的最好，也愿意一起添砖加瓦哈

发自我的iPhone

**Comment by yiding-he** [comment]
分支 1.2.2，单元测试 https://github.com/yiding-he/hydrogen-ssdb/blob/1.2.2/src/test/java/com/hyd/ssdb/SsdbClientTest.java 
其中 testMultiGetBytes() 测试无法通过，找不到原因。

**Comment by darkice1** [comment]
我自己写了一个简单的测试 。应该可以使用。
在 2020年1月4日 +0800 19:36，捏造的信仰 <notifications@github.com>，写道：

**Comment by yiding-he** [comment]
1.2.2 已经发布。该特性的具体使用方法参考单元测试：
- `com.hyd.ssdb.SsdbClientTest#testMultiGetBytes`
- `com.hyd.ssdb.SsdbClientTest#testMultiGetBytes2`

**Comment by darkice1** [comment]
已测试没问题
在 2020年1月6日 +0800 14:27，捏造的信仰 <notifications@github.com>，写道：
