### ISSUE TITLE
并发高了就会报com.hyd.ssdb.SsdbNoClusterAvailableException: NO CLUSTER AVAILABLE错误

### ISSUE THREAD

**Issue by luger1990** [yiding-he/hydrogen-ssdb#27]
我这么初始化的 `SsdbClient ssdbClient = new SsdbClient("10.1.8.16", 8000, 3, "xxxxx");`
但是请求量大了就会报com.hyd.ssdb.SsdbNoClusterAvailableException: NO CLUSTER AVAILABLE错误。是我使用的方式不对吗

**Comment by yiding-he** [comment]
作为客户端，hydrogen-ssdb 提供连接池配置是必须的。你可以看下 `com.hyd.ssdb.conf.Server` 类的构造方法，其中包含了连接池大小的配置。比如其中一个构造方法：

```
public Server(String host, int port, String pass, boolean master, int soTimeout, int poolMaxTotal)
```

其中最后一个参数就是连接池大小。完整构造 `SsdbClient` 的例子如下：

```
int poolSize = 30;
ssdbClient = SsdbClient.fromClusters(Arrays.asList(
    Cluster.fromServers(Arrays.asList(
        new Server("localhost", 8888, null, true, 60, poolSize)
    ))
));
```

**Comment by yiding-he** [comment]
这是个 BUG，原因是参数 3 本来单位是秒，但构造的过程中没有乘以 1000，导致超时时间变成了 3ms。建议暂时换其他构造方式，我这两天修复这个问题。

**Comment by luger1990** [comment]
@yiding-he 点赞！！！   我感觉也是这的问题

**Comment by yiding-he** [comment]
1.2.2 已经发布（源码已推送，中心库的更新需要一段时间）。该问题已修复。

**Comment by luger1990** [comment]
@yiding-he 已经看到最新的了 速度！！！！
