### ISSUE TITLE
这个应该怎么编译呀

### ISSUE THREAD

**Issue by QQxiaoyuyu** [yiding-he/hydrogen-ssdb#31]
你好，我编译的时候报了缺少文件的错误，能帮忙看看吗，正确的编译方式，编译命令是什么呀
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/ClusterConf.java:[3,14] package lombok does not exist
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/ClusterConf.java:[8,2] cannot find symbol
  symbol: class Data
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/ServerConf.java:[5,14] package lombok does not exist
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/ServerConf.java:[7,51] package org.springframework.boot.context.properties does not exist
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/ServerConf.java:[9,2] cannot find symbol
  symbol: class Data
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConf.java:[3,14] package lombok does not exist
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConf.java:[4,51] package org.springframework.boot.context.properties does not exist
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConf.java:[9,2] cannot find symbol
  symbol: class ConfigurationProperties
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConf.java:[10,2] cannot find symbol
  symbol: class Data
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[7,56] package org.springframework.boot.autoconfigure.condition does not exist
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[8,51] package org.springframework.boot.context.properties does not exist
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[15,2] cannot find symbol
  symbol: class EnableConfigurationProperties
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/ServerConf.java:[20,6] cannot find symbol
  symbol:   class NestedConfigurationProperty
  location: class com.hyd.ssdb.springboot.ServerConf
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/ServerConf.java:[23,6] cannot find symbol
  symbol:   class NestedConfigurationProperty
  location: class com.hyd.ssdb.springboot.ServerConf
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[21,6] cannot find symbol

  symbol:   class ConditionalOnMissingBean
  location: class com.hyd.ssdb.springboot.HydrogenSsdbConfigurator
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/ServerConf.java:[21,50] createDefaultPoolConfig() has private access in com.hyd.ssdb.conf.Server
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[24,23] cannot find symbol
  symbol:   method getClusters()
  location: variable config of type com.hyd.ssdb.springboot.HydrogenSsdbConf
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[30,39] cannot find symbol
  symbol:   method getServers()
  location: variable clusterConf of type com.hyd.ssdb.springboot.ClusterConf
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[36,40] cannot find symbol
  symbol:   method getPool()
  location: variable serverConf of type com.hyd.ssdb.springboot.ServerConf
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[37,42] cannot find symbol
  symbol:   method getSocket()
  location: variable serverConf of type com.hyd.ssdb.springboot.ServerConf
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[38,36] cannot find symbol
  symbol:   method isMaster()
  location: variable serverConf of type com.hyd.ssdb.springboot.ServerConf
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[39,34] cannot find symbol
  symbol:   method getHost()
  location: variable serverConf of type com.hyd.ssdb.springboot.ServerConf
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[40,34] cannot find symbol
  symbol:   method getPort()
  location: variable serverConf of type com.hyd.ssdb.springboot.ServerConf
[ERROR] /home/jenkins_data/workspace/ssdbcli-jar/src/main/java/com/hyd/ssdb/springboot/HydrogenSsdbConfigurator.java:[41,34] cannot find symbol

**Comment by yiding-he** [comment]
@QQxiaoyuyu 目前不要用 master 分支编译，这个分支有的功能还没完成。取 1.2.3 分支来编译。

**Comment by QQxiaoyuyu** [comment]
好的，多谢啦
