### ISSUE TITLE
Cluster 模式下，数据量较大时ssdb只读不能更新的问题

### ISSUE THREAD

**Issue by yenohhr** [yiding-he/hydrogen-ssdb#35]
ssdb关键配置参数如下：
leveldb:
        # in MB
        cache_size: 500
        # in MB
        write_buffer_size: 64
        # in MB/s
        compaction_speed: 1000
        # yes|no
        compression: yes

m1、m2、m3是ssdb集群的三个replication，数据库文件大小如下：
[root@iZbp15qbhzylu7lbul26qqZ ~]# du -h --max-depth=1 /data/ssdb/bak/
1.7G    /data/ssdb/bak/m2
1.7G    /data/ssdb/bak/m3
584M    /data/ssdb/bak/m1
3.9G    /data/ssdb/bak/

我通过hydrogen-ssdb连接ssdb时，发现只能读取数据，无法set和del，然后连接大约600秒钟后，出现SocketTimeout错误。

请问一下这个可能是什么问题引发的？

**Comment by yenohhr** [comment]
ECS配置是 4核16G内存

**Comment by yiding-he** [comment]
关于 SocketTimeout 错误，能不能贴出完整的异常堆栈，以便分析问题？

**Comment by yenohhr** [comment]
嗯，非常感谢，QQ：2126422

代码是最常规的你的示例代码
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.myweb.utils.JsonUtil;
import com.google.gson.reflect.TypeToken;
import com.hyd.ssdb.SsdbClient;
import com.hyd.ssdb.conf.Cluster;
import com.hyd.ssdb.conf.Server;
import com.hyd.ssdb.sharding.ConsistentHashSharding;

@Configuration
public class SsdbConfig {
	@Value("${config_path}")
	private String configPath;
	@Bean
	public SsdbClient ssdbClient() throws IOException {
		Type t = new TypeToken<List<HashMap<String, String>>>(){}.getType();
		List<HashMap<String, String>> replications = JsonUtil.loadFile(configPath+"ssdb.properties",t);
		ArrayList<Cluster> list = new ArrayList<Cluster>();
		for(HashMap<String, String> replication:replications) {
			list.add(new Cluster(new Server(replication.get("host"),Integer.parseInt(replication.get("port"))), 100));
		}
		return new SsdbClient(new ConsistentHashSharding(list));
	}
}

**Comment by yenohhr** [comment]
另外，我们发现linux系统里有自动连接断开设置，也就是连接池如果没有处理好连接的心跳检测，保持连接有效性时，会被系统ban掉，从而会出现socketTimeout的错误。

ssdb有没有类似mongodb的连接自动失效和重新创建的功能，比如创建3分钟就失效，而且连接池会再建立新连接，例如：
spring.data.mongodb.maxIdleTimeMS=180000

**Comment by yiding-he** [comment]
根据 @yenohhr 描述，这里需要的是实现连接检测机制。现在已经在[分支 1.2.7](https://github.com/yiding-he/hydrogen-ssdb/tree/1.2.7) 中添加了该机制，同时需要在创建 `SsdbClient` 的过程中增加一些配置。示例如下：

```
Server server = new Server(host, port);
server.getPoolConfig().setTestWhileIdle(true); // 启用测试空闲的连接
server.getPoolConfig().setTimeBetweenEvictionRunsMillis(5000); // 测试间隔时间

SsdbClient ssdbClient = new SsdbClient(server);
```

得到测试通过的反馈（或没有反馈的情况下超过若干天）后，将发布正式版本。

**Comment by yiding-he** [comment]
分支 1.2.7 已经发布到 Maven Central。
